config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  root 'pages#home'
  resources :users, only: [:index] do
    post :impersonate, on: :member
    get :impersonate, on: :member
    post :stop_impersonating, on: :collection
    get :stop_impersonating, on: :collection
  end
   
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: { admin: 0, customer: 1}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#  impersonates :user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin
  def index
    @users = User.all
  end

  def impersonate
    user = User.find(params[:id])
    impersonate_user(user)
    redirect_to root_path
  end

  def stop_impersonating
    stop_impersonating_user
    redirect_to root_path
  end

  private

  def require_admin
    redirect_to  root_path, notice: 'Go away, you are not admin' unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Video</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<p><%= notice %></p>


<% if current_user %>
<h1> HEllo , <%= current_user.email %>!</h1>
<%= link_to 'Log out', destroy_user_session_path, data: { turbo_method: :delete} %>
<% else %>
  <%= link_to 'Sign in', new_user_session_path %>
<% end %>


<br/>

<%= link_to  "Admin Panel", users_path %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>


<ul>
    <% @users.each do |user| %>
      <li>Sign in as <%= link_to user.email, impersonate_user_path(user), method: :post %></li>
    <% end %>
</ul>